[package]
name = "from_formats"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
dlopen = "0.1.8"
dlopen_derive = "0.1.4"
flate2 = "1.0.28"
libc = "0.2.149"
libloading = "0.8.1"

